### ISSUE TITLE
transferImage minor improvements?

### ISSUE THREAD

**Issue by dragon-fish** [DreamOfIce/koishi-plugin-adapter-villa#4]
https://github.com/DreamOfIce/koishi-plugin-adapter-villa/blob/55bd77fea44238b4e055262eb6b76a5e8c0dfba1/src/utils/transferImage.ts#L12

Replace `Record` with `Map`

https://github.com/DreamOfIce/koishi-plugin-adapter-villa/blob/55bd77fea44238b4e055262eb6b76a5e8c0dfba1/src/utils/transferImage.ts#L67

There may be a risk of memory leaks

**Comment by DreamOfIce** [comment]
> There may be a risk of memory leaks

We have deleted it here:
https://github.com/DreamOfIce/koishi-plugin-adapter-villa/blob/55bd77fea44238b4e055262eb6b76a5e8c0dfba1/src/utils/transferImage.ts#L122

**Comment by dragon-fish** [comment]
To my understanding. `ctx.router.get` is called every time `transformImage` is called.

**Comment by dragon-fish** [comment]
The above issues are all fixed by #3

**Comment by DreamOfIce** [comment]
> To my understanding. `ctx.router.get` is called every time `transformImage` is called.

Yes, so the callback will be replace by the new one
